create table customers (
    id bigint generated by default as identity primary key,
    customer_number varchar(30) not null unique,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    date_of_birth date not null,
    email varchar(255) not null,
    phone_number varchar(40),
    status varchar(30) not null,
    risk_score integer not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table addresses (
    id bigint generated by default as identity primary key,
    customer_id bigint not null,
    type varchar(30) not null,
    street_line_1 varchar(255) not null,
    street_line_2 varchar(255),
    postal_code varchar(20) not null,
    city varchar(255) not null,
    country_code varchar(2) not null,
    primary_address boolean not null,
    constraint fk_addresses_customer foreign key (customer_id) references customers (id)
);

create table accounts (
    id bigint generated by default as identity primary key,
    customer_id bigint not null,
    account_number varchar(40) not null unique,
    type varchar(30) not null,
    status varchar(30) not null,
    balance decimal(19, 2) not null,
    opened_date date not null,
    constraint fk_accounts_customer foreign key (customer_id) references customers (id)
);

create table consents (
    id bigint generated by default as identity primary key,
    customer_id bigint not null,
    category varchar(40) not null,
    granted boolean not null,
    captured_at timestamp not null,
    channel varchar(255) not null,
    constraint fk_consents_customer foreign key (customer_id) references customers (id)
);

create table support_cases (
    id bigint generated by default as identity primary key,
    customer_id bigint not null,
    case_number varchar(40) not null unique,
    title varchar(255) not null,
    description varchar(2000) not null,
    status varchar(40) not null,
    priority integer not null,
    opened_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_support_cases_customer foreign key (customer_id) references customers (id)
);

create table audit_events (
    id bigint generated by default as identity primary key,
    customer_number varchar(30) not null,
    event_type varchar(80) not null,
    description varchar(1000) not null,
    created_at timestamp not null,
    created_by varchar(255) not null
);

create index idx_customers_name on customers (last_name, first_name);
create index idx_accounts_customer on accounts (customer_id);
create index idx_addresses_customer on addresses (customer_id);
create index idx_consents_customer on consents (customer_id);
create index idx_support_cases_customer on support_cases (customer_id);
create index idx_audit_customer_number on audit_events (customer_number);
